# s = input()
# E = s.count("E") + s.count("e")
# G = s.count("G") + s.count("g")
# Y = s.count("Y") + s.count("y")
# P = s.count("P") + s.count("p")
# T = s.count("T") + s.count("t")
# n = min(E,G,Y,P,T)
# print(n)
s = input().upper()
print(min(s.count(c) for c in "EGYPT" ))
